trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals agentdevops
jobs:
  # track deployments on the environment
- deployment: DeployWeb
  displayName: deploy Web App
  pool:
    name: Default
    demands:
    - agent.name -equals agentdevops
  # creates an environment if it doesn't exist
  environment: 'vmenv'
  strategy:
    # default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment